[tasks.compose]
command = "docker-compose"
cwd = "integration-tests"
args = [
    "up",
    "--build"
]

[tasks.up]
command = "cargo"
env_files = [".env"]
args = [
    "run",
    "--features",
    "debug"
]
